name: Release Obsidian Plugin
on:
    push:
        tags:
            - "*"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
                  fetch-tags: true

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24.x"

            - name: Get Version
              id: version
              run: |
                  echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

            - name: Build plugin
              id: build
              run: |
                  npm install
                  npm run build --if-present

            - name: Package plugin
              run: |
                  mkdir ${{ github.event.repository.name }}
                  cp main.js manifest.json README.md styles.css ${{ github.event.repository.name }}
                  zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}

            - name: Create Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release create "${{ github.ref_name }}" \
                  --title "${{ github.ref_name }}" \
                  --generate-notes \
                  --verify-tag

            - name: Upload zip file
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAG: ${{ steps.version.outputs.tag }}
                  VERSION_TAG: ${{ steps.version.outputs.tag }}
              run: |
                  gh release upload "$TAG" \
                  "./${GITHUB_REPOSITORY##*/}.zip#${GITHUB_REPOSITORY##*/}-${VERSION_TAG}.zip" \
                  ./main.js \
                  ./manifest.json \
                  ./styles.css \
                  --clobber
